
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Stackathon</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Human Body Facts</h1>

        <p className={styles.description}>
          Explore the marvels of the human body with React, Next.js and Sequelize
        </p>

        <Image
          src="https://images.unsplash.com/photo-1530213786676-41ad9f7736f6?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80"
          alt="human medical model"
          width="450px"
          height="300px"
        />
      </main>
    </div>
  );
}
